apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cfk-oauth-secret.yaml
  - cmf-secret-configmaps.yaml
  - cmfrestclass.yaml
  - flink-application-colors.yaml
  - flink-application-shapes.yaml
  - flink-environment-colors.yaml
  - flink-environment-shapes.yaml
  - flink-oauth-secrets.yaml
  - keycloak-service-account-job.yaml
  - producer-oauth-secrets.yaml
  - producers.yaml
  - schemas.yaml
  - sql-config-configmaps.yaml
  - sql-init-jobs.yaml
  - topics.yaml
