---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: infrastructure
  sources:
    - repoURL: https://aws.github.io/eks-charts
      targetRevision: 1.11.0
      chart: aws-load-balancer-controller
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/infrastructure/aws-load-balancer-controller/base/values.yaml
          - $values/infrastructure/aws-load-balancer-controller/overlays/eks-demo/values.yaml
    - repoURL: https://github.com/osowski/confluent-platform-gitops.git
      targetRevision: v0.7.0
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: ""
      kind: Secret
      name: aws-load-balancer-tls
      namespace: kube-system
      jqPathExpressions:
        - .data["ca.crt"]
        - .data["tls.crt"]
        - .data["tls.key"]
