apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-config.yaml
- infra-ingresses.yaml
- cert-manager.yaml
- cert-manager-resources.yaml
- trust-manager.yaml
- kube-prometheus-stack-crds.yaml
- kube-prometheus-stack.yaml
- metrics-server.yaml
- aws-ebs-csi-driver.yaml
- aws-load-balancer-controller.yaml
- external-dns.yaml
- external-secrets.yaml
- reflector.yaml
- traefik.yaml
- minio.yaml

# Infrastructure applications are deployed in sync wave order (10-85)
# Remove any applications you don't need for your cluster
