apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:8.1.0
    init: confluentinc/confluent-init-container:3.1.0

  # Dependencies - must wait for Kafka broker
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.kafka.svc.cluster.local:9092
