---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: flink
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "flink-colors,flink-shapes"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  labels:
    app: minio
type: Opaque
stringData:
  root-user: "admin"
  root-password: "password"
