---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: keycloak
  annotations:
    # Allow Reflector to mirror this secret to other namespaces
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "flink"
type: Opaque
stringData:
  KEYCLOAK_ADMIN: flink-admin
  KEYCLOAK_ADMIN_PASSWORD: admin123
