---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cmf-server-tls
  namespace: operator
spec:
  secretName: cmf-server-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: cmf-service.operator.svc.cluster.local
  dnsNames:
    - cmf-service
    - cmf-service.operator
    - cmf-service.operator.svc
    - cmf-service.operator.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: cmf-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
