---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cmf-ca-bundle
spec:
  sources:
    - secret:
        name: cmf-root-ca
        key: ca.crt
        # The CA secret is in the cert-manager namespace (created by CA Certificate)
        namespace: cert-manager
  target:
    configMap:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        cmf-mtls: "enabled"
