{
 "title": "Flink",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Application",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime,app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "description": "The number of running jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRunningJobs{job=\"flink-native-kubernetes\", app=\"$env\"})"
    }
   ]
  },
  {
   "title": "Task Slots Total",
   "type": "stat",
   "description": "The total number of task slots.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsTotal{job=\"flink-native-kubernetes\", app=\"$env\"})"
    }
   ]
  },
  {
   "title": "Task Slots Available",
   "type": "stat",
   "description": "The number of available task slots.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsAvailable{job=\"flink-native-kubernetes\", app=\"$env\"})"
    }
   ]
  },
  {
   "title": "Registered Task Managers",
   "type": "stat",
   "description": "The number of registered taskmanagers.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(sum(flink_jobmanager_numRegisteredTaskManagers{job=\"flink-native-kubernetes\", app=\"$env\"})[2m:30s])"
    }
   ]
  },
  {
   "title": "Number of pending task managers",
   "type": "stat",
   "description": "(only applicable to Native Kubernetes / YARN) The number of outstanding taskmanagers that Flink has requested.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numPendingTaskManagers{job=\"flink-native-kubernetes\", app=\"$env\"})"
    }
   ]
  },
  {
   "title": "Number of backpressured tasks",
   "type": "stat",
   "description": "Total number of tasks that are back-pressured.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_isBackPressured{job=\"flink-native-kubernetes\", app=\"$env\"})"
    }
   ]
  },
  {
   "title": "JVM Memory (Heap + Non heap) Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(flink_jobmanager_Status_JVM_Memory_Heap_Used{job=\"flink-native-kubernetes\", app=\"$env\"})",
     "legendFormat": "Heap:{{pod}}"
    },
    {
     "expr": "(flink_jobmanager_Status_JVM_Memory_NonHeap_Used{job=\"flink-native-kubernetes\", app=\"$env\"})",
     "legendFormat": "NonHeap:{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(flink_jobmanager_Status_JVM_Memory_Heap_Max{job=\"flink-native-kubernetes\", app=\"$env\"})",
     "legendFormat": "Heap:{{pod}}"
    },
    {
     "expr": "(flink_jobmanager_Status_JVM_Memory_NonHeap_Max{job=\"flink-native-kubernetes\", app=\"$env\"})",
     "legendFormat": "Nonheap:{{pod}}"
    }
   ]
  },
  {
   "title": "Total Live Threads",
   "type": "timeseries",
   "description": "The total number of live threads.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "(flink_jobmanager_Status_JVM_Threads_Count{job=\"flink-native-kubernetes\", app=\"$env\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Task Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load{job=\"flink-native-kubernetes\", app=\"$env\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Busy Percent",
   "type": "timeseries",
   "description": "1 - (The number of unused memory segments / The number of allocated memory segments)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "1-(flink_taskmanager_Status_Network_AvailableMemorySegments{app=\"$env\"} / flink_taskmanager_Status_Network_TotalMemorySegments{app=\"$env\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Historical Task Managers",
   "type": "timeseries",
   "description": "The number of registered taskmanagers.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time((sum(flink_jobmanager_numRegisteredTaskManagers{job=\"flink-native-kubernetes\", app=\"$env\"}) by (app))[2m:30s])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Num Records In per sec",
   "type": "timeseries",
   "description": "The number of records this operator/task has received per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, task: {{task_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, op: {{operator_id}}"
    }
   ]
  },
  {
   "title": "Bytes In per sec",
   "type": "timeseries",
   "description": "Task/Operator Bytes received per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesInPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, task: {{task_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numBytesInPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, op: {{operator_id}}"
    }
   ]
  },
  {
   "title": "Num Records Out per sec",
   "type": "timeseries",
   "description": "The number of records this operator/task has sent per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsOutPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, task: {{task_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, op: {{operator_id}}"
    }
   ]
  },
  {
   "title": "Bytes Out per sec",
   "type": "timeseries",
   "description": "Task/Operator Bytes sent per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, task: {{task_id}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_numBytesOutPerSecond{job=\"flink-native-kubernetes\", app=\"$env\"}",
     "legendFormat": "{{job_name}}, op: {{operator_id}}"
    }
   ]
  }
 ]
}