apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flink

resources:
  - cmfrestclass.yaml
  - service.yaml
  - flink-environment-default.yaml
  - flink-application-example.yaml
  - topics.yaml
  - schemas.yaml
  - flink-kafka-catalog.yaml
  - flink-kafka-database.yaml
  - flink-compute-pool.yaml

# Common labels applied to all resources
labels:
- includeSelectors: false
  includeTemplates: true  
  pairs:
    app.kubernetes.io/part-of: confluent-flink
    app.kubernetes.io/managed-by: argocd
