apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

bases:
  - ../../base

patches:
  - path: kafka-broker-patch.yaml
    target:
      kind: Kafka
      name: kafka
  - path: schema-registry-ingress-patch.yaml
    target:
      kind: IngressRoute
      name: schema-registry
