---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: rustfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
