---
apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: rustfs
type: Opaque
stringData:
  access-key: "admin"
  secret-key: "password"
