apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Exclude ollama namespace — only needed for flink-demo clusters
resources:
  - ../../base/operator.yaml
  - ../../base/kafka.yaml
  - ../../base/flink.yaml
