---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/osowski/confluent-platform-gitops.git
    targetRevision: feature-145/fix-cmf-catalog-architecture
    path: workloads/flink-rbac/overlays/flink-demo-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
