apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cmf-rest-class-basic-secret.yaml

components:
  - ../../components/oauth

patches:
  - path: cmfrestclass-ldap-basic-patch.yaml

labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    cluster: flink-demo-rbac
