apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-tls
  namespace: vault
spec:
  dnsNames:
  - vault.CLUSTER_NAME.DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: vault-server-tls
  usages:
  - digital signature
  - key encipherment
