---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "75"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/osowski/confluent-platform-gitops.git
    targetRevision: v0.2.0
    path: infrastructure/cert-manager-resources/overlays/flink-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
