---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20" # Deploy after cert-manager and storage
spec:
  project: infrastructure
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      targetRevision: v1.19.2 # Pin to specific version
      chart: cert-manager
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/infrastructure/cert-manager/base/values.yaml
          - $values/infrastructure/cert-manager/overlays/flink-demo/values.yaml
    - repoURL: https://github.com/osowski/confluent-platform-gitops
      targetRevision: v0.2.0
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Required for CRDs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
