---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: schema-registry-tls
  namespace: kafka
spec:
  secretName: schema-registry-tls
  dnsNames:
    - schema-registry.eks-demo.platform.dspdemos.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
