apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Cluster-specific patches
patches:
  - path: keycloak-patch.yaml
    target:
      kind: StatefulSet
      name: keycloak

  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: keycloak-tls

  - path: ingress-patch.yaml
    target:
      kind: IngressRoute
      name: keycloak

  - path: realm-sync-job-patch.yaml
    target:
      kind: Job
      name: keycloak-realm-sync

# Cluster-specific labels
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    cluster: flink-demo-rbac-mtls
