---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: minio
type: Opaque
stringData:
  root-user: "admin"
  root-password: "password"
