---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3proxy-data
  namespace: flink
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
