---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy
  namespace: flink
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app: s3proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: s3proxy
