apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-resources-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "120"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/osowski/confluent-platform-gitops.git
    targetRevision: HEAD
    path: workloads/flink-resources-rbac/overlays/eks-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
