---
clusterName: eks-demo
region: us-east-1
vpcId: vpc-0f3e3de0efc336067

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::829250931565:role/AWSLoadBalancerController_eks-demo
