---
clusterName: eks-demo
region: us-east-1
vpcId: vpc-04b988b7882ab2bcf

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::829250931565:role/AWSLoadBalancerController_eks-demo
