apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: kafka
spec:
  replicas: 2
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  authorization:
    type: rbac

  dependencies:
    kafka:
      bootstrapEndpoint: kafka.kafka.svc.cluster.local:9071
      authentication:
        type: oauth
        jaasConfig:
          secretRef: kafka-oauth-client
        oauthSettings:
          subClaimName: client_id
          tokenEndpointUri: http://keycloak.keycloak.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/token

    mds:
      endpoint: http://kafka.kafka.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: oauth
        oauth:
          secretRef: kafka-oauth-client
          configuration:
            tokenEndpointUri: http://keycloak.keycloak.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/token
            expectedIssuer: https://keycloak.eks-demo.platform.dspdemos.com/realms/confluent
            jwksEndpointUri: http://keycloak.keycloak.svc.cluster.local:8080/realms/confluent/protocol/openid-connect/certs
            subClaimName: client_id
