---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headlamp.flink-demo-rbac-mtls.confluentdemo.local`)
      kind: Rule
      services:
        - name: headlamp
          port: 80
          scheme: http
  tls:
    secretName: headlamp-tls
