---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cmf
  namespace: operator
spec:
  routes:
    - match: Host(`cmf.flink-demo.confluentdemo.local`)
      kind: Rule
      services:
        - name: cmf-service
          port: 80
          scheme: http
