apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  dnsNames:
  - argocd.CLUSTER_NAME.DOMAIN
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: argocd-server-tls
  usages:
  - digital signature
  - key encipherment
