apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openldap

resources:
  - namespace.yaml
  - admin-secret.yaml
  - mds-bind-secret.yaml
  - seed-ldif-configmap.yaml
  - acl-bootstrap-configmap.yaml
  - openldap.yaml
  - seed-job.yaml
