---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-model-config
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app: ollama
data:
  models: |
    qwen3:8b
