---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: flink
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi
