---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  labels:
    app: ollama
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 11434
    targetPort: api
    protocol: TCP
  selector:
    app: ollama
