apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "110"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/osowski/confluent-platform-gitops.git
    targetRevision: HEAD
    path: workloads/confluent-resources/overlays/flink-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
