apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "120"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/osowski/confluent-platform-gitops.git
    targetRevision: HEAD
    path: workloads/flink-resources/overlays/flink-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
