apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cfk-operator.yaml
  - cmf-operator.yaml
  - confluent-resources.yaml
  - flink-agents.yaml
  - flink-kubernetes-operator.yaml
  - flink-resources.yaml
  - namespaces.yaml
  - observability-resources.yaml
  #- ollama.yaml ## DISABLED temporarily in favor of running Ollama locally on MacBooks
  - workload-ingresses.yaml
