apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "117"  # After Flink operator (wave 116)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/osowski/confluent-platform-gitops.git
    targetRevision: HEAD
    path: workloads/observability-resources/base
  destination:
    server: https://kubernetes.default.svc
    namespace: operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false  # Namespace should already exist from wave 100
